#!/usr/bin/env ruby

# gems
require 'colorize'
require 'inkjet'

# modules
require 'json'

# files
require_relative './lib/start_menu.rb'
require_relative './lib/room.rb'
require_relative './lib/room_list.rb'
require_relative './lib/new_character.rb'
require_relative './lib/character.rb'
require_relative './lib/player.rb'
require_relative './lib/player_list.rb'
require_relative './lib/play_game.rb'
require_relative './lib/ascii_image.rb'

# Specify JSON library files
PLAYER_CLASSES = './lib/player_classes.json'.freeze
PLAYERS_DATABASE = './lib/saved_characters.json'
WORLD_DATABASE = './lib/rooms.json'.freeze

# Load start menu if no argument passed.
if ARGV.length.zero?
  puts `clear`
  start_menu_selection
# Load existing character passed as argument and start game.  
elsif ARGV.length == 1
  load_game(ARGV[0])
else
  puts "You have entered to many arguments. You can enter your character name as an argument to load your character (e.g ./adventure -aragorn) or nothing to launch the start menu."
end
